--------------------------------------------------------
--  파일이 생성됨 - 수요일-3월-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "MOREMORE"."COMPANY" 
   (	"COMPANY_NO" NUMBER, 
	"USER_NO" NUMBER, 
	"COMPANY_NAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "MOREMORE"."COMPANY"."COMPANY_NO" IS '기업번호';
   COMMENT ON COLUMN "MOREMORE"."COMPANY"."USER_NO" IS '회원번호';
   COMMENT ON COLUMN "MOREMORE"."COMPANY"."COMPANY_NAME" IS '기업명';
REM INSERTING into MOREMORE.COMPANY
SET DEFINE OFF;
Insert into MOREMORE.COMPANY (COMPANY_NO,USER_NO,COMPANY_NAME) values (4,3,'펀딩회사');
--------------------------------------------------------
--  DDL for Index PK_COMPANY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOREMORE"."PK_COMPANY" ON "MOREMORE"."COMPANY" ("COMPANY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "MOREMORE"."COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY ("COMPANY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOREMORE"."COMPANY" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."COMPANY" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."COMPANY" MODIFY ("COMPANY_NO" NOT NULL ENABLE);
