--------------------------------------------------------
--  파일이 생성됨 - 수요일-3월-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DELIVERY
--------------------------------------------------------

  CREATE TABLE "MOREMORE"."DELIVERY" 
   (	"DELIVERY_NO" NUMBER, 
	"DELIVERY_NAME" VARCHAR2(50 BYTE), 
	"DELIVERY_ADDRESS" VARCHAR2(100 BYTE), 
	"DELIVERY_ADDRESS_NUMER" VARCHAR2(50 BYTE), 
	"DELIVERY_ADDRESS_PHONE" VARCHAR2(50 BYTE), 
	"DELIVERY_ARRIVAL_DATE" DATE, 
	"DELIVERY_CLASS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "MOREMORE"."DELIVERY"."DELIVERY_NO" IS '배송지 번호';
   COMMENT ON COLUMN "MOREMORE"."DELIVERY"."DELIVERY_NAME" IS '수령인 이름';
   COMMENT ON COLUMN "MOREMORE"."DELIVERY"."DELIVERY_ADDRESS" IS '수령인 주소';
   COMMENT ON COLUMN "MOREMORE"."DELIVERY"."DELIVERY_ADDRESS_NUMER" IS '수령인 우편번호';
   COMMENT ON COLUMN "MOREMORE"."DELIVERY"."DELIVERY_ADDRESS_PHONE" IS '수령인 연락처';
   COMMENT ON COLUMN "MOREMORE"."DELIVERY"."DELIVERY_ARRIVAL_DATE" IS '물품수령일';
   COMMENT ON COLUMN "MOREMORE"."DELIVERY"."DELIVERY_CLASS" IS '배송지구분';
REM INSERTING into MOREMORE.DELIVERY
SET DEFINE OFF;
Insert into MOREMORE.DELIVERY (DELIVERY_NO,DELIVERY_NAME,DELIVERY_ADDRESS,DELIVERY_ADDRESS_NUMER,DELIVERY_ADDRESS_PHONE,DELIVERY_ARRIVAL_DATE,DELIVERY_CLASS) values (1,'윤효민','인천남구용현동','44434','010-000-0000',to_date('22/10/04','RR/MM/DD'),'구분');
Insert into MOREMORE.DELIVERY (DELIVERY_NO,DELIVERY_NAME,DELIVERY_ADDRESS,DELIVERY_ADDRESS_NUMER,DELIVERY_ADDRESS_PHONE,DELIVERY_ARRIVAL_DATE,DELIVERY_CLASS) values (2,'전지현','서울강남구','44434','010-000-0000',to_date('22/10/04','RR/MM/DD'),'구분');
--------------------------------------------------------
--  DDL for Index PK_DELIVERY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOREMORE"."PK_DELIVERY" ON "MOREMORE"."DELIVERY" ("DELIVERY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DELIVERY
--------------------------------------------------------

  ALTER TABLE "MOREMORE"."DELIVERY" ADD CONSTRAINT "PK_DELIVERY" PRIMARY KEY ("DELIVERY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOREMORE"."DELIVERY" MODIFY ("DELIVERY_CLASS" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."DELIVERY" MODIFY ("DELIVERY_ARRIVAL_DATE" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."DELIVERY" MODIFY ("DELIVERY_ADDRESS_PHONE" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."DELIVERY" MODIFY ("DELIVERY_ADDRESS_NUMER" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."DELIVERY" MODIFY ("DELIVERY_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."DELIVERY" MODIFY ("DELIVERY_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."DELIVERY" MODIFY ("DELIVERY_NO" NOT NULL ENABLE);
