--------------------------------------------------------
--  파일이 생성됨 - 수요일-3월-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDER_DETAIL
--------------------------------------------------------

  CREATE TABLE "MOREMORE"."ORDER_DETAIL" 
   (	"ORDER_DETAIL_NO" NUMBER, 
	"GOODS_NO" NUMBER, 
	"ORDER_NO" NUMBER, 
	"DELIVERY_NO" NUMBER, 
	"ORDER_EA" NUMBER, 
	"ORDER_STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "MOREMORE"."ORDER_DETAIL"."ORDER_DETAIL_NO" IS '주문순차번호';
   COMMENT ON COLUMN "MOREMORE"."ORDER_DETAIL"."GOODS_NO" IS '상품번호';
   COMMENT ON COLUMN "MOREMORE"."ORDER_DETAIL"."ORDER_NO" IS '주문번호';
   COMMENT ON COLUMN "MOREMORE"."ORDER_DETAIL"."DELIVERY_NO" IS '배송지번호';
   COMMENT ON COLUMN "MOREMORE"."ORDER_DETAIL"."ORDER_EA" IS '구매수량';
   COMMENT ON COLUMN "MOREMORE"."ORDER_DETAIL"."ORDER_STATUS" IS '주문현황';
REM INSERTING into MOREMORE.ORDER_DETAIL
SET DEFINE OFF;
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (1,2,1,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (2,5,2,2,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (3,9,3,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (4,10,4,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (5,14,5,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (6,17,6,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (7,19,7,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (8,24,8,1,2,'반품완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (9,25,9,1,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (10,30,10,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (11,4,11,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (12,7,12,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (13,11,13,1,5,'반품완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (14,15,14,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (15,16,15,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (16,20,16,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (17,22,17,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (18,27,18,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (19,32,19,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (20,35,20,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (21,37,21,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (22,42,22,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (23,8,23,1,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (24,17,24,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (25,33,25,2,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (26,55,26,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (27,44,27,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (28,2,28,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (29,10,29,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (30,54,30,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (31,46,31,2,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (32,49,32,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (33,19,33,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (34,33,34,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (35,35,35,1,5,'반품완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (36,37,36,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (37,40,37,2,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (38,43,38,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (39,47,39,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (40,51,40,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (41,53,41,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (42,56,42,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (43,33,43,2,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (44,34,44,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (45,37,45,1,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (46,41,46,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (47,8,47,2,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (48,16,48,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (49,32,49,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (50,55,50,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (51,43,51,1,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (52,1,52,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (53,10,53,2,3,'반품완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (54,53,54,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (55,46,55,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (56,51,56,2,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (57,52,57,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (58,57,58,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (59,31,59,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (60,36,60,2,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (61,37,61,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (62,41,62,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (63,40,63,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (64,7,64,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (65,18,65,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (66,33,66,2,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (67,56,67,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (68,43,68,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (69,3,69,2,4,'반품완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (70,11,70,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (71,54,71,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (72,48,72,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (73,50,73,1,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (74,49,74,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (75,52,75,2,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (76,55,76,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (77,31,77,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (78,36,78,2,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (79,37,79,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (80,40,80,1,1,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (81,41,81,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (82,7,82,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (83,18,83,1,10,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (84,14,84,2,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (85,16,85,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (86,20,86,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (87,24,87,2,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (88,25,88,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (89,29,89,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (90,5,90,1,7,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (91,8,91,1,5,'반품완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (92,11,92,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (93,57,93,2,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (94,43,94,1,7,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (95,2,95,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (96,12,96,2,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (97,54,97,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (98,46,98,1,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (99,50,99,1,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (100,51,100,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (101,52,101,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (102,56,102,2,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (103,31,103,1,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (104,1,104,1,9,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (105,11,105,2,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (106,52,106,1,7,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (107,46,107,1,5,'반품완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (108,50,108,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (109,20,109,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (110,32,110,1,7,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (111,35,111,2,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (112,37,112,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (113,41,113,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (114,45,114,2,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (115,48,115,1,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (116,49,116,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (117,9,117,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (118,16,118,1,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (119,32,119,1,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (120,56,120,2,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (121,45,121,1,2,'반품완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (122,2,122,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (123,11,123,2,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (124,53,124,1,9,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (125,52,125,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (126,13,126,1,7,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (127,18,127,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (128,20,128,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (129,23,129,2,7,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (130,27,130,1,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (131,30,131,1,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (132,5,132,2,3,'반품완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (133,8,133,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (134,12,134,2,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (135,13,135,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (136,18,136,1,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (137,20,137,2,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (138,24,138,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (139,25,139,1,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (140,31,140,1,9,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (141,34,141,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (142,37,142,1,7,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (143,40,143,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (144,41,144,2,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (145,7,145,1,7,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (146,17,146,1,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (147,32,147,2,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (148,55,148,1,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (149,45,149,1,4,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (150,3,150,1,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (151,10,151,1,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (152,54,152,2,2,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (153,48,153,1,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (154,51,154,1,6,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (155,54,155,2,9,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (156,55,156,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (157,31,157,1,7,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (158,34,158,2,5,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (159,27,159,1,3,'구매확정');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (160,30,160,1,7,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (161,4,161,2,5,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (162,7,162,1,6,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (163,11,163,1,9,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (164,14,164,2,3,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (165,18,165,1,7,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (166,20,166,1,5,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (167,24,167,1,3,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (168,25,168,1,7,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (169,33,169,1,4,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (170,34,170,1,2,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (171,28,171,2,5,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (172,17,172,1,6,'반품완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (173,21,173,1,4,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (174,23,174,2,2,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (175,25,175,1,2,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (176,28,176,1,5,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (177,4,177,1,6,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (178,8,178,1,9,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (179,12,179,2,3,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (180,13,180,1,7,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (181,18,181,1,5,'반품신청');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (182,20,182,1,3,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (183,16,183,2,7,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (184,20,184,1,3,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (185,22,185,1,7,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (186,26,186,2,5,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (187,30,187,1,6,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (188,4,188,1,9,'반품신청');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (189,7,189,1,4,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (190,12,190,1,2,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (191,14,191,1,2,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (192,17,192,2,5,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (193,21,193,1,6,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (194,50,194,2,9,'반품신청');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (195,54,195,1,3,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (196,56,196,1,7,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (197,31,197,2,5,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (198,34,198,1,3,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (199,37,199,1,4,'주문완료');
Insert into MOREMORE.ORDER_DETAIL (ORDER_DETAIL_NO,GOODS_NO,ORDER_NO,DELIVERY_NO,ORDER_EA,ORDER_STATUS) values (200,13,200,1,1,'주문완료');
--------------------------------------------------------
--  DDL for Index PK_ORDER_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOREMORE"."PK_ORDER_DETAIL" ON "MOREMORE"."ORDER_DETAIL" ("ORDER_DETAIL_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ORDER_DETAIL
--------------------------------------------------------

  ALTER TABLE "MOREMORE"."ORDER_DETAIL" ADD CONSTRAINT "PK_ORDER_DETAIL" PRIMARY KEY ("ORDER_DETAIL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOREMORE"."ORDER_DETAIL" MODIFY ("ORDER_STATUS" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."ORDER_DETAIL" MODIFY ("ORDER_EA" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."ORDER_DETAIL" MODIFY ("DELIVERY_NO" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."ORDER_DETAIL" MODIFY ("ORDER_NO" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."ORDER_DETAIL" MODIFY ("GOODS_NO" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."ORDER_DETAIL" MODIFY ("ORDER_DETAIL_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ORDER_DETAIL
--------------------------------------------------------

  ALTER TABLE "MOREMORE"."ORDER_DETAIL" ADD CONSTRAINT "FK_GOODS_TO_ORDER_DETAIL_1" FOREIGN KEY ("GOODS_NO")
	  REFERENCES "MOREMORE"."GOODS" ("GOODS_NO") ENABLE;
  ALTER TABLE "MOREMORE"."ORDER_DETAIL" ADD CONSTRAINT "FK_ORDERS_TO_ORDER_DETAIL_1" FOREIGN KEY ("ORDER_NO")
	  REFERENCES "MOREMORE"."ORDERS" ("ORDER_NO") ENABLE;
  ALTER TABLE "MOREMORE"."ORDER_DETAIL" ADD CONSTRAINT "FK_ORDERS_TO_ORDER_DETAIL_2" FOREIGN KEY ("DELIVERY_NO")
	  REFERENCES "MOREMORE"."DELIVERY" ("DELIVERY_NO") ENABLE;
