--------------------------------------------------------
--  파일이 생성됨 - 수요일-3월-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROJECT_CATEGORY
--------------------------------------------------------

  CREATE TABLE "MOREMORE"."PROJECT_CATEGORY" 
   (	"PRO_CATENO" NUMBER, 
	"PRO_CATENAME" VARCHAR2(300 BYTE), 
	"PRO_CATE_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "MOREMORE"."PROJECT_CATEGORY"."PRO_CATENO" IS '카테고리번호';
   COMMENT ON COLUMN "MOREMORE"."PROJECT_CATEGORY"."PRO_CATENAME" IS '카테고리명';
   COMMENT ON COLUMN "MOREMORE"."PROJECT_CATEGORY"."PRO_CATE_TYPE" IS '카테고리타입';
REM INSERTING into MOREMORE.PROJECT_CATEGORY
SET DEFINE OFF;
Insert into MOREMORE.PROJECT_CATEGORY (PRO_CATENO,PRO_CATENAME,PRO_CATE_TYPE) values (1,'테크','테크');
Insert into MOREMORE.PROJECT_CATEGORY (PRO_CATENO,PRO_CATENAME,PRO_CATE_TYPE) values (2,'반려동물','반려동물');
Insert into MOREMORE.PROJECT_CATEGORY (PRO_CATENO,PRO_CATENAME,PRO_CATE_TYPE) values (3,'여행','여행');
Insert into MOREMORE.PROJECT_CATEGORY (PRO_CATENO,PRO_CATENAME,PRO_CATE_TYPE) values (4,'뷰티','뷰티');
Insert into MOREMORE.PROJECT_CATEGORY (PRO_CATENO,PRO_CATENAME,PRO_CATE_TYPE) values (5,'푸드','푸드');
Insert into MOREMORE.PROJECT_CATEGORY (PRO_CATENO,PRO_CATENAME,PRO_CATE_TYPE) values (6,'홈리빙','홈리빙');
--------------------------------------------------------
--  DDL for Index PK_PROJECT_CATEGORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOREMORE"."PK_PROJECT_CATEGORY" ON "MOREMORE"."PROJECT_CATEGORY" ("PRO_CATENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROJECT_CATEGORY
--------------------------------------------------------

  ALTER TABLE "MOREMORE"."PROJECT_CATEGORY" ADD CONSTRAINT "PK_PROJECT_CATEGORY" PRIMARY KEY ("PRO_CATENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOREMORE"."PROJECT_CATEGORY" MODIFY ("PRO_CATE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."PROJECT_CATEGORY" MODIFY ("PRO_CATENAME" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."PROJECT_CATEGORY" MODIFY ("PRO_CATENO" NOT NULL ENABLE);
