--------------------------------------------------------
--  파일이 생성됨 - 수요일-3월-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "MOREMORE"."REVIEW" 
   (	"REVIEW_NO" NUMBER, 
	"USER_NO" NUMBER, 
	"PRO_NO" NUMBER, 
	"REVIEW_CONTENT" VARCHAR2(1000 BYTE), 
	"REVIEW_SCORE" VARCHAR2(100 BYTE), 
	"REVIEW_REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "MOREMORE"."REVIEW"."REVIEW_NO" IS '리뷰번호';
   COMMENT ON COLUMN "MOREMORE"."REVIEW"."USER_NO" IS '회원번호';
   COMMENT ON COLUMN "MOREMORE"."REVIEW"."PRO_NO" IS '프로젝트번호';
   COMMENT ON COLUMN "MOREMORE"."REVIEW"."REVIEW_CONTENT" IS '내용';
   COMMENT ON COLUMN "MOREMORE"."REVIEW"."REVIEW_SCORE" IS '평점';
   COMMENT ON COLUMN "MOREMORE"."REVIEW"."REVIEW_REGDATE" IS '작성일자';
REM INSERTING into MOREMORE.REVIEW
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOREMORE"."PK_REVIEW" ON "MOREMORE"."REVIEW" ("REVIEW_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "MOREMORE"."REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("REVIEW_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOREMORE"."REVIEW" MODIFY ("REVIEW_REGDATE" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."REVIEW" MODIFY ("REVIEW_SCORE" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."REVIEW" MODIFY ("REVIEW_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."REVIEW" MODIFY ("PRO_NO" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."REVIEW" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."REVIEW" MODIFY ("REVIEW_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "MOREMORE"."REVIEW" ADD CONSTRAINT "FK_PROJECT_TO_REVIEW_1" FOREIGN KEY ("PRO_NO")
	  REFERENCES "MOREMORE"."PROJECT" ("PRO_NO") ENABLE;
