--------------------------------------------------------
--  파일이 생성됨 - 수요일-3월-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "MOREMORE"."STOCK" 
   (	"GOODS_NO" NUMBER, 
	"GOODS_STOCK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "MOREMORE"."STOCK"."GOODS_NO" IS '상품번호';
   COMMENT ON COLUMN "MOREMORE"."STOCK"."GOODS_STOCK" IS '상품재고';
REM INSERTING into MOREMORE.STOCK
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_STOCK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOREMORE"."PK_STOCK" ON "MOREMORE"."STOCK" ("GOODS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "MOREMORE"."STOCK" ADD CONSTRAINT "PK_STOCK" PRIMARY KEY ("GOODS_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOREMORE"."STOCK" MODIFY ("GOODS_STOCK" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."STOCK" MODIFY ("GOODS_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "MOREMORE"."STOCK" ADD CONSTRAINT "FK_GOODS_TO_STOCK_1" FOREIGN KEY ("GOODS_NO")
	  REFERENCES "MOREMORE"."GOODS" ("GOODS_NO") ENABLE;
