--------------------------------------------------------
--  파일이 생성됨 - 수요일-3월-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WISHLIST
--------------------------------------------------------

  CREATE TABLE "MOREMORE"."WISHLIST" 
   (	"PRO_NO" NUMBER, 
	"USER_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "MOREMORE"."WISHLIST"."PRO_NO" IS '프로젝트번호';
   COMMENT ON COLUMN "MOREMORE"."WISHLIST"."USER_NO" IS '회원번호';
REM INSERTING into MOREMORE.WISHLIST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOREMORE"."PK_LIKE" ON "MOREMORE"."WISHLIST" ("PRO_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table WISHLIST
--------------------------------------------------------

  ALTER TABLE "MOREMORE"."WISHLIST" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY ("PRO_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOREMORE"."WISHLIST" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "MOREMORE"."WISHLIST" MODIFY ("PRO_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table WISHLIST
--------------------------------------------------------

  ALTER TABLE "MOREMORE"."WISHLIST" ADD CONSTRAINT "FK_PROJECT_TO_LIKE_1" FOREIGN KEY ("PRO_NO")
	  REFERENCES "MOREMORE"."PROJECT" ("PRO_NO") ENABLE;
